CREATE TABLE IF NOT EXISTS suppliers(
supplierID INT PRIMARY KEY AUTO_INCREMENT,
supplierName VARCHAR(255) NOT NULL,
ContactNumber VARCHAR(255),
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 deleted_at TIMESTAMP
);



CREATE TABLE IF NOT EXISTS products(
ProductID INT PRIMARY KEY AUTO_INCREMENT,
ProductName VARCHAR(255) NOT NULL,
Price DECIMAL(10,2),
 StockQuantity INT NOT NULL,
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 deleted_at TIMESTAMP,
SupplierID INT FOREIGN KEY (SupplierID)REFERENCES suppliers(supplierID)
);


CREATE TABLE IF NOT EXISTS sales(
saleID INT PRIMARY KEY AUTO_INCREMENT,
quantitySold INT,
salesDate DATE,
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 deleted_at TIMESTAMP,
productID INT FOREIGN KEY (productID) REFERENCES products(productID)
);